#!/bin/sh

# update_timers: retrieve a new "merkliste" from http://tvtv.de,
# convert it to vdr format and transmit it to vdr via SVDRP.

TOOLDIR="/home/cko/bin"
CHANPATH="/home/cko/VDR/channels.conf"

cd /tmp
rm -f merkliste.html

# if you have a slow dial up connection to your name server and/or ISP,
# this will avoid a timeout in get_merkliste.pl.
ping -c 2 www.tvtv.de

# get the "merkliste".
$TOOLDIR/get_merkliste.pl

if [ -s merkliste.html ] ; then
   # convert merkliste.html to timers.conf format and transmit it to vdr.
   $TOOLDIR/epg2timers $CHANPATH < merkliste.html | $TOOLDIR/loadvdr.pl
fi
