#!/bin/sh

DVBDIR="../DVB/driver"
VDRPRG="./vdr"
VDRCMD="$VDRPRG -w 60"

KILLPROC="/sbin/killproc -TERM"

while (true) do
#      (cd $DVBDIR; make reload)
#      sleep 3
      if $VDRCMD; then exit; fi
      date
      echo "restarting VDR"
      $KILLPROC $VDRPRG
      sleep 10
      done
